services:
  app:
    build:
      context: .
      target: development
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?user=postgres&password=postgres
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .

  db:
    image: 'postgres:16.3-alpine'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_SERVER: db
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
